apiVersion: v1
kind: Service
metadata:
  name: complete-production-e2e-svc
spec:
  type: NodePort
  selector:
    app: complete-production-e2e-deployment
  ports:
    - port: 80
      targetPort: 8080
